apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  labels:
    deploy: jaeger
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:1.16.0@sha256:738442983b772a5d413c8a2c44a5563956adaff224e5b38f52a959124dafc119
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: false
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
